const {
  AMMO_HOST = "http://f-am.hz.ds.se.com",
  BAND_HOST = "http://t-bd.hz.ds.se.com",
  CLASSIC2_HOST = "http://t-cc.hz.ds.se.com",
  DRUM_GQL_URI = "https://ds-api-test.energymost.com",
  ELECTRONIC_APP_HOST = "http://test-di-app.hz.ds.se.com/test/electronic/apphost",
  ELECTRONIC_UI_DOCKER_API_BASE_PATH = "https://web-api-test.itm.energymost.com",
  FLUTE_HOST = "http://t-fl.hz.ds.se.com",
  FORT_HOST = "http://t-ft.hz.ds.se.com",
  FUNK_APP_HOST = "http://test-da-app.hz.ds.se.com/test/funk/apphost",
  FUNK_UI_DOCKER_API_BASE_PATH = "https://web-api-test.da.energymost.com",
  GUITAR_HOST = "http://t-gr.hz.ds.se.com",
  HARDCORE_HOST = "http://f-hce.hz.ds.se.com",
  HIPHOP_APP_HOST = "http://test-mm-app.hz.ds.se.com/test/hiphop/apphost",
  HIPHOP_UI_DOCKER_API_BASE_PATH = "https://web-api-test.mm.energymost.com",
  JAZZ_APP_HOST = "http://test-em-app.hz.ds.se.com/test/jazz/apphost",
  JAZZ_OPENWEBAPI_HOST = "http://internalapi-em-test.hz.ds.se.com/test/jazz/openwebapi",
  JAZZ_WEBAPI_HOST = "https://web-api-test.energymost.com",
  POKEMON_HOST = "http://t-pm.hz.ds.se.com",
  POLKA_APP_HOST = "http://test-de-app.hz.ds.se.com/test/polka/apphost",
  POLKA_UI_API_BASE_PATH = "https://web-api-de-test.energymost.com",
  POP_APP_HOST = "http://test-fm-app.hz.ds.se.com/test/pop/apphost",
  POP_APP_WEBSOCKET_ADDRESS = "https://wss-test.fm.energymost.com",
  POP_UI_DOCKER_API_BASE_PATH = "https://web-api-test.fm.energymost.com",
  PUNK_URI = "https://punk-test.energymost.com",
  SELEARN_HOST = "http://f-ln.hz.ds.se.com",
  SEYAN_HOST_URL = "https://seyan-api-test.energymost.com",
  VIOLIN_HOST = "http://t-vl.hz.ds.se.com",
  YUMMY_DA_HOST = "http://t-ymda.hz.ds.se.com",
  YUMMY_FM_HOST = "http://t-ymfm.hz.ds.se.com",
  YUMMY_ITM_HOST = "http://t-ymitm.hz.ds.se.com",
  YUMMY_MM_HOST = "http://t-ymmm.hz.ds.se.com"
} = process.env;

export const SourceMap: { [key: string]: string } = {
  AMMO: AMMO_HOST,
  BAND: BAND_HOST,
  CLASSIC: CLASSIC2_HOST,
  DRUM_GQL: DRUM_GQL_URI,
  ELECTRONIC_APP: ELECTRONIC_APP_HOST,
  ELECTRONIC_WEB: ELECTRONIC_UI_DOCKER_API_BASE_PATH,
  FLUTE: FLUTE_HOST,
  FORT: FORT_HOST,
  FUNK_APP: FUNK_APP_HOST,
  FUNK_WEB: FUNK_UI_DOCKER_API_BASE_PATH,
  GUITAR: GUITAR_HOST,
  HARDCORE: HARDCORE_HOST,
  HIPHOP_APP: HIPHOP_APP_HOST,
  HIPHOP_WEB: HIPHOP_UI_DOCKER_API_BASE_PATH,
  JAZZ_APP: JAZZ_APP_HOST,
  JAZZ_WEB: JAZZ_WEBAPI_HOST,
  JAZZ_WEB_OPEN: JAZZ_OPENWEBAPI_HOST,
  POKEMON: POKEMON_HOST,
  POLKA_APP: POLKA_APP_HOST,
  POLKA_WEB: POLKA_UI_API_BASE_PATH,
  POP_APP: POP_APP_HOST,
  POP_APP_WS: POP_APP_WEBSOCKET_ADDRESS,
  POP_WEB: POP_UI_DOCKER_API_BASE_PATH,
  PUNK: PUNK_URI,
  SELEARN: SELEARN_HOST,
  SEYAN: SEYAN_HOST_URL,
  VIOLIN: VIOLIN_HOST,
  YUMMY_DA: YUMMY_DA_HOST,
  YUMMY_FM: YUMMY_FM_HOST,
  YUMMY_ITM: YUMMY_ITM_HOST,
  YUMMY_MM: YUMMY_MM_HOST
};
